### ISSUE TITLE
Can't read indexs

### ISSUE THREAD

**Issue by spartakos87** [osPlanning/omx-python#1]
Hello I have an omx file and I can read what my array contains but not the indexs,sets
For example I have this array
----|a3|a4
a1 | x |x
a2 | x |x
whith the commnad file['name of table'].read() I get only the xs, but I want to take and the a1,a2,..etc
Any suggetion?

**Comment by bstabler** [comment]
I think you want use to the [mappings](https://github.com/osPlanning/omx-python#mappings)
```
myfile.list_mappings()
tazs = myfile.mapping('taz') 
```

**Comment by spartakos87** [comment]
I cant just when I read  an matrice
for example

myfile[myfile.list_matrices[0]].read()
to have and the mapping??
Because i want to extract it to excel file 
Thx

**Comment by bstabler** [comment]
The mappings are a separate thing, so how you want to include them (for example as a "first" column in a matrix of numbers) depends on your specific need.  By separating the matrix from the mappings, you are able to "combine" them as you see fit.
