### ISSUE TITLE
Export of matrices from python to PTV VISUM

### ISSUE THREAD

**Issue by raplam** [osPlanning/omx-python#10]
Hello,

I have two OMX matrices:
- a matrix 'matrix_from_VISUM.omx' that I generated in PTV VISUM using the AddIn OMX Export,
- a matrix 'matrix_from_omx-python.omx', that I generated using omx-python.

Both have the same size.

PTV VISUM can import 'matrix_from_VISUM.omx' in a few seconds but needs ages to import 'matrix_from_omx-python.omx' (if it works at all)

I tried to inspect 'matrix_from_VISUM.omx' to reproduce the same matrix attributes in 'matrix_from_omx-python.omx ('NAME', 'CODE', 'MATRIXTYPE', etc.) but it didn't solve the problem.

What should I do differently?

Thanks

**Comment by bstabler** [comment]
Have you compared the outputs of both files with the omx validator?

https://colab.research.google.com/drive/1PUoNc1o-n1042F-xmTH9MEMxramvduHr

**Comment by raplam** [comment]
Thanks for the link. I found out where the problem was: PTV VISUM can successfully import OMX sub-matrices but it takes much longer. The VISUM version I was working with included about 9'000 zones (8'000 inside Switzerland, 1'000 abroad) and the matrix I was generating using omx-python was for the 8'000 zones only. After adding zeros and adjusting the mapping, the import time dropped from 12 min to a few seconds.
