### ISSUE TITLE
Incorrect version being saved

### ISSUE THREAD

**Issue by PeterKucirek** [osPlanning/omx-python#2]
It looks like the Python OMX API is using the `__version__` property rather than the `__omx_version__` property when writing new files:

```python
import openmatrix as omx

source = "test_file.omx"
target = "test_file_out.omx"

with omx.open_file(source, mode='r') as reader, omx.open_file(target, mode='w') as writer:
    print('Source Version', reader.version())
    print('Target Version', writer.version())
```

yields:
```
>> Source Version [b'0.2']
>> Target Version 0.3.3
```

This is causing issue with other OMX libraries (Java in my case) which are asserting the OMX version to be `0.2`.

Also, it looks like the `__omx_version__` global variable is not even defined in the module, contrary to what the Wiki says:

```python
omx.__omx_version__
>>AttributeError: module 'openmatrix' has no attribute '__omx_version__'
```

**Comment by PeterKucirek** [comment]
Quick update: This looks like a version control issue. When I `pip install` from a local clone of the Python library, the problem goes away. But the version on PyPI appears to be out-of-sync with the GitHub repo.

**Comment by bstabler** [comment]
Thanks for tracking this down.  I'll get it fixed.

**Comment by bstabler** [comment]
Fixed - https://pypi.python.org/pypi/OpenMatrix
